#ifndef _COLLISION_LAYERS_H_
#define _COLLISION_LAYERS_H_

enum CollisionLayer
{
	LAYER_EVERYTHING,
	LAYER_PLAYER,
	LAYER_PLAYER_ATTACKS,
	LAYER_ENEMY_ATTACKS,
	LAYER_ENEMIES,
	END_OF_COLLISION_LAYER
};


#endif//_COLLISION_LAYERS_H_